# Generated by Django 6.0.2 on 2026-02-05 15:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='이벤트 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('event_date', models.DateField(verbose_name='이벤트 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR 코드')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '이벤트',
                'verbose_name_plural': '이벤트',
                'ordering': ['-event_date'],
            },
        ),
    ]
