# Generated by Django 6.0.2 on 2026-02-05 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='사진')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('uploader_name', models.CharField(blank=True, max_length=100, verbose_name='업로더 이름')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event', verbose_name='이벤트')),
            ],
            options={
                'verbose_name': '사진',
                'verbose_name_plural': '사진',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
